[project]
name = "rila-ai-agent"
version = "0.1.0"
description = "RILA AI Agent to upload blog from docx to Notion"
requires-python = ">=3.11,<3.12"

[project.scripts]
app = "app.main:app"

[tool.vercel]
framework = "python"
